remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

logo: /assets/img/profile_picture.jpg
title: Alexandre HILTCHER
description: Senior Software & DevOps Engineer

summary:
  - I have been a full-stack software development engineer since 2019, with a strong commitment to software quality as my top priority. 
  - I believe that Clean Code and DevOps are fundamental best practices that ensure maintainability, efficiency, and long-term success. In today’s agile environments, development processes should enhance quality rather than encourage rushed delivery.
  - Passionate about challenges, I am eager to work on complex projects and explore innovative technologies. I thrive in environments that foster continuous learning and personal growth, always striving to push my skills further.